### ISSUE TITLE
Extension host crashes

### ISSUE THREAD

**Issue by rollecode** [Microsoft/vscode-jscs#25]
I have no idea what causes this. Does not happen on all projects.

Here's the devtools console log:

```
/Users/rolle/.vscode/extensions/ms-vscode.jscs-0.1.9/node_modules/vscode-jsonrpc/lib/messageReader.js:155                    throw new Error('Header must provide a Content-Length property.'); 

Error: Header must provide a Content-Length property.
at StreamMessageReader.onData (/Users/rolle/.vscode/extensions/ms-vscode.jscs-0.1.9/node_modules/vscode-jsonrpc/lib/messageReader.js:155:27)
at Socket.<anonymous> (/Users/rolle/.vscode/extensions/ms-vscode.jscs-0.1.9/node_modules/vscode-jsonrpc/lib/messageReader.js:140:19)
at Socket.emit (events.js:223:5)
at Socket.EventEmitter.emit (domain.js:475:20)
at addChunk (_stream_readable.js:309:12)
at readableAddChunk (_stream_readable.js:290:11)
at Socket.Readable.push (_stream_readable.js:224:10)
at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by rollecode** [comment]
Okay it happens on every project today. Still the same error. Edited to add line breaks.

**Comment by mjbvz** [comment]
Closing since we are deprecating this extension (#27) and do not plan any further fixes
